# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./frontend/cv_maker/package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining app files
COPY ./frontend/cv_maker/ ./

# Expose the port the app runs on
EXPOSE 3000

# Run the React app
CMD ["npm", "start"]
