# Generated by Django 5.0.1 on 2024-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='educations',
            field=models.ManyToManyField(blank=True, to='api.education'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='api.experience'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
    ]
