# Generated by Django 5.0.3 on 2024-03-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofilephoto'),
        ),
    ]
